### ISSUE TITLE
firebase json tree

### ISSUE THREAD

**Issue by rotomoco** [eralha/firebase-cms#2]
Dear @eralha ,
thank you for coding this.
I´m a bloody beginner in those angular/firbase things, and learn with your project many things!
Could you please show me, how the firebase-jsontree in your database looks like? Or could you, for better learning and understanding your app, share the *.json?
Thank You!

**Comment by eralha** [comment]
Hi, i'm glad that this project could be useful. 

Here you have the database .json example:
https://github.com/eralha/firebase-cms/blob/master/data-base-example.json

And here you have the .json for firebase rules:
https://github.com/eralha/firebase-cms/blob/master/rules-example.json

If i can provide any more details, please let me know,
Regards.

**Comment by rotomoco** [comment]
Hi there,
thanks!! This will help me out!!
Regards
Roland

**Comment by rotomoco** [comment]
Hi once again,
sorry, but what i have to insert in config.json?
```[{
  "firebaseRef"	: "??",  //the firebaseio? the firebaseapp URL?
  "categoriasRef"	: "categorias",
  "imagensRef"	: "imagens",
  "paginasRef"		: "paginas"
}]
```

**Comment by eralha** [comment]
Don't put nothing there, It was there as a reference for the database, used in old SDK, as i have updated to the new SDK this should be blank, that config needs to be done on this file now:
https://github.com/eralha/firebase-cms/blob/master/index.html#L31

I will remove this reference on a future commit, i just need to check if this is present on the code base.

Regards.
